### ISSUE TITLE
Allow // @noflow?

### ISSUE THREAD

**Issue by FezVrasta** [eirikurn/eslint-plugin-flow-header#1]
Hi, thanks for the awesome lib!

May you add an option, or make it by default, so that I can define `// @noflow` at the top of a file and don't have this rule complain about this file?

I use this rule to avoid to forget to put the `// @flow` comment in my files, but if I explicitly define `// @noflow` I don't expect this rule to yell at me.

**Comment by eirikurn** [comment]
Good point. I had already thought about this, but forgot to implement it. I'll look into it.

**Comment by eirikurn** [comment]
Fixed in a36735bfcc8e541de5c3e0e99ba4d5c578690c15 and published as v0.2.0.

**Comment by FezVrasta** [comment]
Thanks!
